site_name: Mapotic documentation
nav:
    - Home: index.md
    - Map: map.md
    - Geo: geo.md
    - Category: category.md
    - Attribute: attribute.md

theme:
    name: material
    logo: assets/logo.png
    palette:
        primary: green

plugins:
    - mermaid2

    - info:
        enabled: true

markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - attr_list
  - md_in_html
#  - pymdownx.superfences